application: alexaverbuch
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: assets/css

- url: /img
  static_dir: assets/img

- url: /js
  static_dir: assets/js
  
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  

- url: /.*
  script: alexaverbuch.app

libraries:

- name: webapp2
  version: "2.5.1"
  
- name: jinja2
  version: "2.6"